import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "astro/zod";
import seabuckthorn from "../../seabuckthorn.config.ts";

const brandSchema = z.object({
  primary: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
  secondary: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
  accent: z.string().regex(/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$/),
  fontFamily: z.string().min(1),
  logo: z.string().optional(),
  favicon: z.string().optional(),
});

const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);

const outFile = path.join(repoRoot, "src/styles/themes/brand.generated.css");
const manifestFile = path.join(repoRoot, "src/generated/theme-manifest.json");

function generateBrandCss(brand: z.infer<typeof brandSchema>): string {
  return `/* Generated by seabuckthorn brand-theme integration — do not edit */
:root {
  --brand-primary: ${brand.primary};
  --brand-secondary: ${brand.secondary};
  --brand-accent: ${brand.accent};
  --font-family-sans: ${brand.fontFamily};
  --accent: ${brand.accent};
  --focus-ring: ${brand.primary};
}
`;
}

export function brandThemePlugin() {
  return {
    name: "seabuckthorn-brand-theme",
    enforce: "pre" as const,
    buildStart() {
      const brand = (seabuckthorn as { brand?: unknown }).brand;
      if (brand) {
        const parsed = brandSchema.parse(brand);
        fs.mkdirSync(path.dirname(outFile), { recursive: true });
        fs.writeFileSync(outFile, generateBrandCss(parsed), "utf8");
      } else if (fs.existsSync(outFile)) {
        fs.unlinkSync(outFile);
      }

      fs.mkdirSync(path.dirname(manifestFile), { recursive: true });
      fs.writeFileSync(
        manifestFile,
        JSON.stringify({
          themes: seabuckthorn.themes,
          defaultTheme: seabuckthorn.defaultTheme,
        }),
        "utf8",
      );
    },
  };
}
